In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, confusion_matrix, accuracy_score, recall_score

In [2]:
df = pd.read_csv("Social_Media_Advertising.csv")

In [3]:
df = pd.read_csv("Social_Media_Advertising.csv", nrows=1000)

In [4]:
if df.select_dtypes(include=['object']).shape[1] > 0:
    df = pd.get_dummies(df, drop_first=True)

In [5]:
if df.isnull().sum().sum() > 0:
    df = df.dropna()

In [6]:
cov_matrix = df.cov()
print("Covariance Matrix:\n", cov_matrix)

Covariance Matrix:
                          Campaign_ID  Conversion_Rate          ROI  \
Campaign_ID             6.573211e+10       149.882191 -2951.549769   
Conversion_Rate         1.498822e+02         0.001639    -0.003262   
ROI                    -2.951550e+03        -0.003262     6.086508   
Clicks                  1.110852e+06        -0.163269   133.506678   
Impressions             5.426402e+06        -0.827295   653.833480   
...                              ...              ...          ...   
Company_Vigor Valley    6.922921e+02        -0.000383    -0.008614   
Company_Vital Vigor    -3.926180e+02         0.000078    -0.001855   
Company_Vogue Visions   5.818131e+02         0.000171    -0.000715   
Company_Well Wish      -1.107943e+03        -0.000194    -0.015828   
Company_Wellness Waves -3.953599e+02         0.000080    -0.009949   

                              Clicks   Impressions  Engagement_Score  \
Campaign_ID             1.110852e+06  5.426402e+06      17955.83848

In [7]:
df.columns

Index(['Campaign_ID', 'Conversion_Rate', 'ROI', 'Clicks', 'Impressions',
       'Engagement_Score', 'Target_Audience_Men 18-24',
       'Target_Audience_Men 25-34', 'Target_Audience_Men 35-44',
       'Target_Audience_Men 45-60',
       ...
       'Company_Silk & Style', 'Company_Space Spruce', 'Company_Style Sphere',
       'Company_Tech Titans', 'Company_Trend Tailors', 'Company_Vigor Valley',
       'Company_Vital Vigor', 'Company_Vogue Visions', 'Company_Well Wish',
       'Company_Wellness Waves'],
      dtype='object', length=413)

In [8]:
X = df.drop(columns=["Impressions"])                 # Replace "Purchased" with target column name
Y = df["Impressions"]

In [9]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.2, random_state=42)

In [10]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [11]:
logreg = LogisticRegression()
# fit the model with data
logreg.fit(xtrain,ytrain)
# y_pred=logreg.predict(xtest)

LogisticRegression()

In [12]:
# Predict on training data
y_pred_train = logreg.predict(xtrain)

# Predict on test data
y_pred_test = logreg.predict(xtest)

In [13]:
# Precision
precision_train = precision_score(ytrain, y_pred_train, average='weighted')
precision_test = precision_score(ytest, y_pred_test, average='weighted')

# Recall
recall_train = recall_score(ytrain, y_pred_train, average='weighted')
recall_test = recall_score(ytest, y_pred_test, average='weighted')

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [15]:
from sklearn.metrics import confusion_matrix

# Confusion Matrix for Training and Testing
cm_train = confusion_matrix(ytrain, y_pred_train)
cm_test = confusion_matrix(ytest, y_pred_test)

# Now print
print("Confusion Matrix (Train):\n", cm_train)
print("Confusion Matrix (Test):\n", cm_test)

Confusion Matrix (Train):
 [[2 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Confusion Matrix (Test):
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
from sklearn.metrics import accuracy_score

# Ensure Predictions Exist
y_pred_train = logreg.predict(xtrain)
y_pred_test = logreg.predict(xtest)

# Compute Accuracy
accuracy_train = accuracy_score(ytrain, y_pred_train)
accuracy_test = accuracy_score(ytest, y_pred_test)

# Now print
print("\nAccuracy (Train):", accuracy_train)
print("Accuracy (Test):", accuracy_test)



Accuracy (Train): 1.0
Accuracy (Test): 0.0


In [18]:
print("\nPrecision (Train):", precision_train)


Precision (Train): 1.0


In [19]:
print("Precision (Test):", precision_test)

Precision (Test): 0.0


In [20]:
print("\nRecall (Train):", recall_train)


Recall (Train): 1.0


In [21]:
print("Recall (Test):", recall_test)

Recall (Test): 0.0
